name: pl_and_user
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  file_picker: ^5.5.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Haddii aad leedahay images ama fonts, ku dar halkan:
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont.ttf
